"""Initial migration

Revision ID: 4159cd642c21
Revises: 
Create Date: 2026-09-17 01:03:56.615320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4159cd642c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_outbox_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('time_format', sa.String(), server_default=sa.text("'24h'"), nullable=False),
    sa.Column('locale', sa.String(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('en', 'ru')", name='ck_app_user_locale'),
    sa.CheckConstraint("time_format IN ('12h', '24h')", name='ck_app_user_time_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('app_activation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_activation_code_user_id'), 'app_activation_code', ['user_id'], unique=False)
    op.create_table('app_password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_password_reset_code_user_id'), 'app_password_reset_code', ['user_id'], unique=False)
    op.create_table('app_project',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), server_default=sa.text("'#9E9E9E'"), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('round_to_hour', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("color IN ('#F44336', '#FF9800', '#FFEB3B', '#4CAF50', '#00CCCC', '#2196F3', '#3F51B5', '#9C27B0', '#E91E63', '#9E9E9E')", name='ck_app_project_color'),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_app_project_status'),
    sa.CheckConstraint('hourly_rate IS NULL OR hourly_rate >= 0', name='ck_app_project_hourly_rate'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_project_user_id'), 'app_project', ['user_id'], unique=False)
    op.create_table('app_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("revoke_reason IS NULL OR revoke_reason IN ('rotated', 'revoked')", name='ck_app_refresh_token_revoke_reason'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_refresh_token_family_id'), 'app_refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('ix_app_refresh_token_token_hash'), 'app_refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_app_refresh_token_user_id'), 'app_refresh_token', ['user_id'], unique=False)
    op.create_table('app_timer',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Interval(), sa.Computed('end_time - start_time', persisted=True), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('round_to_hour', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('billable_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR end_time > start_time', name='ck_app_timer_end_after_start'),
    sa.CheckConstraint('hourly_rate IS NULL OR hourly_rate >= 0', name='ck_app_timer_hourly_rate'),
    sa.ForeignKeyConstraint(['project_id'], ['app_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_timer_project_id'), 'app_timer', ['project_id'], unique=False)
    op.create_index(op.f('ix_app_timer_user_id'), 'app_timer', ['user_id'], unique=False)
    op.create_index('uq_app_timer_running_per_user', 'app_timer', ['user_id'], unique=True, postgresql_where=sa.text('end_time IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_app_timer_running_per_user', table_name='app_timer', postgresql_where=sa.text('end_time IS NULL'))
    op.drop_index(op.f('ix_app_timer_user_id'), table_name='app_timer')
    op.drop_index(op.f('ix_app_timer_project_id'), table_name='app_timer')
    op.drop_table('app_timer')
    op.drop_index(op.f('ix_app_refresh_token_user_id'), table_name='app_refresh_token')
    op.drop_index(op.f('ix_app_refresh_token_token_hash'), table_name='app_refresh_token')
    op.drop_index(op.f('ix_app_refresh_token_family_id'), table_name='app_refresh_token')
    op.drop_table('app_refresh_token')
    op.drop_index(op.f('ix_app_project_user_id'), table_name='app_project')
    op.drop_table('app_project')
    op.drop_index(op.f('ix_app_password_reset_code_user_id'), table_name='app_password_reset_code')
    op.drop_table('app_password_reset_code')
    op.drop_index(op.f('ix_app_activation_code_user_id'), table_name='app_activation_code')
    op.drop_table('app_activation_code')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('app_outbox_email')
    # ### end Alembic commands ###
